# Generated by Django 4.1.2 on 2022-10-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacionesprueba1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maestro',
            unique_together=set(),
        ),
    ]
