# Generated by Django 4.0.7 on 2022-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacionesprueba1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptos',
            name='idd',
            field=models.AutoField(db_column='IDD', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='idd_concepto',
            field=models.DecimalField(db_column='idd_Concepto', decimal_places=0, max_digits=18),
        ),
    ]
