# Generated by Django 4.0.7 on 2022-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacionesprueba1', '0002_alter_certificaciones_agrupamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imagen',
            field=models.BinaryField(blank=True, db_column='Imagen', null=True),
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='clave',
            field=models.BinaryField(db_column='Clave'),
        ),
        migrations.AlterField(
            model_name='sysdiagrams',
            name='definition',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
