# Generated by Django 4.0.7 on 2022-10-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacionesprueba1', '0003_alter_personas_imagen_alter_seguridad_clave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': True, 'ordering': ['-idd']},
        ),
    ]
