USE [master]
GO

/****** Object:  Database [certificaciones]    Script Date: 5/10/2022 12:51:57 ******/
CREATE DATABASE [certificaciones] ON  PRIMARY 
( NAME = N'certificaciones', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\certificaciones.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'certificaciones_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\certificaciones_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [certificaciones].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [certificaciones] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [certificaciones] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [certificaciones] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [certificaciones] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [certificaciones] SET ARITHABORT OFF 
GO

ALTER DATABASE [certificaciones] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [certificaciones] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [certificaciones] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [certificaciones] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [certificaciones] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [certificaciones] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [certificaciones] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [certificaciones] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [certificaciones] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [certificaciones] SET  DISABLE_BROKER 
GO

ALTER DATABASE [certificaciones] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [certificaciones] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [certificaciones] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [certificaciones] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [certificaciones] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [certificaciones] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [certificaciones] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [certificaciones] SET RECOVERY FULL 
GO

ALTER DATABASE [certificaciones] SET  MULTI_USER 
GO

ALTER DATABASE [certificaciones] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [certificaciones] SET DB_CHAINING OFF 
GO

ALTER DATABASE [certificaciones] SET  READ_WRITE 
GO

